DMS Web Source/II-VI Incorporated SCM/Controllers/Account/GroupsAdminController.cs
using II_VI_Incorporated_SCM.Models.Account;
using Microsoft.AspNet.Identity.Owin;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace II_VI_Incorporated_SCM.Controllers.Account
{
    [Authorize(Roles = "Admin")]
    public class GroupsAdminController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        private ApplicationGroupManager _groupManager;
        public ApplicationGroupManager GroupManager
        {
            get
            {
                return _groupManager ?? new ApplicationGroupManager();
            }
            private set
            {
                _groupManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext()
                    .Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }


        public ActionResult Index()
        {
            return View(this.GroupManager.Groups.ToList());
        }


        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationGroup applicationgroup =
                await this.GroupManager.Groups.FirstOrDefaultAsync(g => g.Id == id);
            if (applicationgroup == null)
            {
                return HttpNotFound();
            }
            var groupRoles = this.GroupManager.GetGroupRoles(applicationgroup.Id);
            string[] RoleNames = groupRoles.Select(p => p.Name).ToArray();
            ViewBag.RolesList = RoleNames;
            ViewBag.RolesCount = RoleNames.Count();
            return View(applicationgroup);
        }


        public ActionResult Create()
        {
            //Get a SelectList of Roles to choose from in the View:
            //ViewBag.RolesList = new SelectList(
            //    this.RoleManager.Roles.ToList(), "Id", "Name");

            ViewBag.RolesList = 
                this.RoleManager.Roles.OrderBy(r => r.Group).ToList();
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(
            [Bind(Include = "Name,Description")] GroupViewModel GroupViewModel, params string[] selectedRoles)
        {
            if (ModelState.IsValid)
            {
                // Create the new Group:
                var applicationgroup = new ApplicationGroup(GroupViewModel.Name, GroupViewModel.Description);
                var result = await this.GroupManager.CreateGroupAsync(applicationgroup);
                if (result.Succeeded)
                {
                    selectedRoles = selectedRoles ?? new string[] { };

                    // Add the roles selected:
                    await this.GroupManager.SetGroupRolesAsync(applicationgroup.Id, selectedRoles);
                }
                return RedirectToAction("Index");
            }

            // Otherwise, start over:
            ViewBag.RolesList =
                this.RoleManager.Roles.OrderBy(r => r.Group).ToList();
            return View(GroupViewModel);
        }


        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationGroup applicationgroup = await this.GroupManager.FindByIdAsync(id);
            if (applicationgroup == null)
            {
                return HttpNotFound();
            }

            // Get a list, not a DbSet or queryable:
            var allRoles = await this.RoleManager.Roles.ToListAsync();
            var groupRoles = await this.GroupManager.GetGroupRolesAsync(id);

            var model = new GroupViewModel()
            {
                Id = applicationgroup.Id,
                Name = applicationgroup.Name,
                Description = applicationgroup.Description
            };

            // load the roles/Roles for selection in the form:
            foreach (var Role in allRoles)
            {
                var listItem = new RoleViewModel()
                {
                    Group = Role.Group,
                    Name = Role.Name,
                    Id = Role.Id,
                    Selected = groupRoles.Any(g => g.Id == Role.Id)
                };
                model.RolesList.Add(listItem);
            }
            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(
            [Bind(Include = "Id,Name,Description")] GroupViewModel model, params string[] selectedRoles)
        {
            var group = await this.GroupManager.FindByIdAsync(model.Id);
            if (group == null)
            {
                return HttpNotFound();
            }
            if (ModelState.IsValid)
            {
                group.Name = model.Name;
                group.Description = model.Description;
                await this.GroupManager.UpdateGroupAsync(group);

                selectedRoles = selectedRoles ?? new string[] { };
                await this.GroupManager.SetGroupRolesAsync(group.Id, selectedRoles);
                return RedirectToAction("Index");
            }
            return View(model);
        }


        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationGroup applicationgroup = await this.GroupManager.FindByIdAsync(id);
            if (applicationgroup == null)
            {
                return HttpNotFound();
            }
            return View(applicationgroup);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationGroup applicationgroup = await this.GroupManager.FindByIdAsync(id);
            await this.GroupManager.DeleteGroupAsync(id);
            return RedirectToAction("Index");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DMS Web Source/II-VI Incorporated SCM/Views/GroupsAdmin/Create.cshtml
@model II_VI_Incorporated_SCM.Models.Account.GroupViewModel
@{
    ViewBag.Title = "Create New Group Role";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h2>@ViewBag.Title</h2>
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
            </div>
          
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.TextBoxFor(model => model.Description, new { @class = "form-control" })
            </div>
            <div class="col-md-6">
                @Html.ValidationMessageFor(model => model.Description, null, new { @class = "help-block text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-2 control-label">
                Select Group Roles
            </label>
            <div class="col-md-4">
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Role Name</th>
                            <th>Module</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in (List<II_VI_Incorporated_SCM.Models.Account.ApplicationRole>)ViewBag.RolesList)
                        {
                            <tr>
                                <td><input type="checkbox" name="SelectedRoles" value="@item.Name" class="checkbox-inline" /></td>
                                <td>@Html.Label(item.Name, new { @class = "control-label" })</td>
                                <td>@Html.Label(item.Group, new { @class = "control-label" })</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <div class="col-md-6">
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-info" })
</div>
@*@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@

DMS Web Source/II-VI Incorporated SCM/Views/GroupsAdmin/Delete.cshtml
@model II_VI_Incorporated_SCM.Models.Account.ApplicationGroup

@{
    ViewBag.Title = "Delete Group Role";
}
<h2>@ViewBag.Title</h2>
<h3>Are you sure you want to delete this?</h3>
@using (Html.BeginForm("Delete", "GroupsAdmin", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        <label for="Name" class="col-sm-2 control-label"><b>Group Role name:</b></label>
        <div class="col-sm-10">
            <p class="form-control-static">@Model.Name</p>
        </div>
    </div>
    <div class="form-group">
        <label for="Name" class="col-sm-2 control-label"><b>Description:</b></label>
        <div class="col-sm-10">
            <p class="form-control-static">@Model.Description</p>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <input type="submit" value="Delete" class="btn btn-danger" />
        </div>
    </div>
}
@Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-info" })
@*<div>
    <h4>Group Role</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>*@

DMS Web Source/II-VI Incorporated SCM/Views/GroupsAdmin/Details.cshtml
@model II_VI_Incorporated_SCM.Models.Account.ApplicationGroup
@{
    ViewBag.Title = "Group Role Details";
}
<div>
    <h2>@ViewBag.Title</h2>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<h4>List of Roles granted this group</h4>
@if (ViewBag.PermissionsCount == 0)
{
    <hr />
    <p>No users found in this Role.</p>
}
<table class="table">
    @foreach (var item in ViewBag.RolesList)
    {
        <tr>
            <td>
                @item
            </td>
        </tr>
    }
</table>
<div class="row">
    <div class="col-md-offset-1 col-md-11">
        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-info" }) |
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-warning" })
    </div>
</div>

DMS Web Source/II-VI Incorporated SCM/Views/GroupsAdmin/Edit.cshtml
@model II_VI_Incorporated_SCM.Models.Account.GroupViewModel
@{
    ViewBag.Title = "Edit Group Role";
}
@*<h2>Edit</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>ApplicationGroup</h4>
            <hr />
            @Html.ValidationSummary(true)
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name)
                    @Html.ValidationMessageFor(model => model.Name)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description)
                    @Html.ValidationMessageFor(model => model.Description)
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Permissions", new { @class = "control-label col-md-2" })
                <span class=" col-md-10">
                    @foreach (var item in Model.RolesList)
                    {
                        <div>
                            <input type="checkbox" name="selectedRoles" value="@item.Text" checked="@item.Selected" class="checkbox-inline" />
                            @Html.Label(item.Text, new { @class = "control-label" })
                        </div>
                    }
                </span>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }*@

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.Id)
    <div class="form-horizontal">
        <h2>@ViewBag.Title</h2>
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
            </div>
            <div class="col-md-6">
                @Html.ValidationMessageFor(model => model.Name, null, new { @class = "help-block text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.TextBoxFor(model => model.Description, new { @class = "form-control" })
            </div>
            <div class="col-md-6">
                @Html.ValidationMessageFor(model => model.Description, null, new { @class = "help-block text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-2 control-label">
                Select Group Roles
            </label>
            <div class="col-md-4">
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Role Name</th>
                            <th>Module</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.RolesList)
                        {
                            <tr>
                                <td><input type="checkbox" name="selectedRoles" value="@item.Name" checked="@item.Selected" class="checkbox-inline" /></td>
                                <td>@Html.Label(item.Name, new { @class = "control-label" })</td>
                                <td>@Html.Label(item.Group, new { @class = "control-label" })</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <div class="col-md-6">
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-warning" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-info" })
</div>
@*@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@

DMS Web Source/II-VI Incorporated SCM/Views/GroupsAdmin/Index.cshtml
@model IEnumerable<II_VI_Incorporated_SCM.Models.Account.ApplicationGroup>
@{
    ViewBag.Title = "Group Roles Management";
}
<h2>@ViewBag.Title</h2>
<p>
    @Html.ActionLink("Create New Group Role", "Create", null, new { @class = "btn btn-success" })
</p>
<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-warning" }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-info" }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
                </td>
            </tr>
        }
    </tbody>
</table>