DMS Web Source/II-VI Incorporated SCM/Controllers/Account/RolesAdminController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Collections.Generic;
using II_VI_Incorporated_SCM.Models.Account;

namespace II_VI_Incorporated_SCM.Controllers.Account
{
    [Authorize(Roles = "Admin")]
    public class RolesAdminController : Controller
    {
        public RolesAdminController()
        {
        }

        public RolesAdminController(ApplicationUserManager userManager,
            ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        //
        // GET: /Roles/
        public ActionResult Index()
        {
            return View(RoleManager.Roles);
        }

        //
        // GET: /Roles/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            // Get the list of Users in this Role
            var users = new List<ApplicationUser>();

            // Get the list of Users in this Role
            foreach (var user in UserManager.Users.ToList())
            {
                if (await UserManager.IsInRoleAsync(user.Id, role.Name))
                {
                    users.Add(user);
                }
            }

            ViewBag.Users = users;
            ViewBag.UserCount = users.Count();
            return View(role);
        }

        //
        // GET: /Roles/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Roles/Create
        [HttpPost]
        public async Task<ActionResult> Create(RoleViewModel roleViewModel)
        {
            if (ModelState.IsValid)
            {
                var role = new ApplicationRole(roleViewModel.Name, roleViewModel.Group);
                var roleresult = await RoleManager.CreateAsync(role);
                if (!roleresult.Succeeded)
                {
                    ModelState.AddModelError("", roleresult.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }

        //
        // GET: /Roles/Edit/Admin
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            RoleViewModel roleModel = new RoleViewModel { Id = role.Id, Name = role.Name, Group = role.Group };
            return View(roleModel);
        }

        //
        // POST: /Roles/Edit/5
        [HttpPost]

        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Group,Name,Id")] RoleViewModel roleModel)
        {
            if (ModelState.IsValid)
            {
                var role = await RoleManager.FindByIdAsync(roleModel.Id);
                role.Name = roleModel.Name;
                role.Group = roleModel.Group;
                await RoleManager.UpdateAsync(role);
                return RedirectToAction("Index");
            }
            return View();
        }

        //
        // GET: /Roles/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        //
        // POST: /Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id, string deleteUser)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                var role = await RoleManager.FindByIdAsync(id);
                if (role == null)
                {
                    return HttpNotFound();
                }
                IdentityResult result;
                if (deleteUser != null)
                {
                    result = await RoleManager.DeleteAsync(role);
                }
                else
                {
                    result = await RoleManager.DeleteAsync(role);
                }
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

DMS Web Source/II-VI Incorporated SCM/Views/RolesAdmin/Create.cshtml
@model II_VI_Incorporated_SCM.Models.Account.RoleViewModel
@{
    ViewBag.Title = "Create New Role";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h2>@ViewBag.Title.</h2>
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
            </div>
            <div class="col-md-6">
                @Html.ValidationMessageFor(model => model.Name, null, new { @class = "help-block text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Group, new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.DropDownListFor(model => model.Group, new List<SelectListItem>
                {
                    new SelectListItem{ Text="NCR", Value = "NCR" },
                    new SelectListItem{ Text="SCAR", Value = "SCAR" },
                    new SelectListItem{ Text="Report", Value = "Report" },
                      new SelectListItem{ Text="ProductTranfer", Value = "ProductTranfer" },
                 }, "- Please Select -", new { @class = "form-control" })
            </div>
            <div class="col-md-6">
                @Html.ValidationMessageFor(model => model.Group, null, new { @class = "help-block text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-info" })
</div>
@*@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@

DMS Web Source/II-VI Incorporated SCM/Views/RolesAdmin/Delete.cshtml
@model II_VI_Incorporated_SCM.Models.Account.ApplicationRole
@{
    ViewBag.Title = "Delete Role";
}
<h2>@ViewBag.Title.</h2>
<h3>Are you sure you want to delete this Role?</h3>
<p>Deleting this Role will remove all users from this role. It will not delete the users.</p>
<hr />
@using (Html.BeginForm("Delete", "RolesAdmin", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        <label for="Name" class="col-sm-2 control-label"><b>Role name:</b></label>
        <div class="col-sm-10">
            <p class="form-control-static">@Model.Name</p>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <input type="submit" value="Delete" class="btn btn-danger" />
        </div>
    </div>
}
@Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-info" })

DMS Web Source/II-VI Incorporated SCM/Views/RolesAdmin/Details.cshtml
@model II_VI_Incorporated_SCM.Models.Account.ApplicationRole
@{
    ViewBag.Title = "Role Details";
}
<div>
    <h2>@ViewBag.Title</h2>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            Module
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Group)
        </dd>
    </dl>
</div>
<h4>List of users in this role</h4>
@if (ViewBag.UserCount == 0)
{
    <hr />
    <p>No users found in this Role.</p>
}
<table class="table">
    @foreach (var item in ViewBag.Users)
    {
        <tr>
            <td>
                @item.UserName
            </td>
        </tr>
    }
</table>
<div class="row">
    <div class="col-md-offset-1 col-md-11">
        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-info" }) |
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-warning" })
    </div>
</div>

DMS Web Source/II-VI Incorporated SCM/Views/RolesAdmin/Edit.cshtml
@model II_VI_Incorporated_SCM.Models.Account.RoleViewModel

@{
    ViewBag.Title = "Edit Role";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h2>@ViewBag.Title.</h2>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)
        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
            </div>
            <div class="col-md-6">
                @Html.ValidationMessageFor(model => model.Name, null, new { @class = "help-block text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Group, new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.DropDownListFor(model => model.Group, new List<SelectListItem>
                {
                    new SelectListItem{ Text="NCR", Value = "NCR" },
                    new SelectListItem{ Text="SCAR", Value = "SCAR" },
                    new SelectListItem{ Text="Report", Value = "Report" },
                    new SelectListItem{ Text="Administrator", Value = "Administrator" },
                 }, "- Please Select -", new { @class = "form-control" })
            </div>
            <div class="col-md-6">
                @Html.ValidationMessageFor(model => model.Group, null, new { @class = "help-block text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-warning" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-info" })
</div>

@*@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@

DMS Web Source/II-VI Incorporated SCM/Views/RolesAdmin/Index.cshtml
@model IEnumerable<II_VI_Incorporated_SCM.Models.Account.ApplicationRole>

@{
    ViewBag.Title = "Roles Management";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Create New Role", "Create", null, new { @class = "btn btn-success" })
</p>
<table class="table table-striped">
    <thead>
        <tr>
            <th>
                Role Name
            </th>
            <th>
                Module
            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Group)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-warning" }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-info" }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
                </td>
            </tr>
        }
    </tbody>
</table>