DMS Web Source/II-VI Incorporated SCM/Controllers/NCR/WriteNCRForIQCController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using II_VI_Incorporated_SCM.Models;
using II_VI_Incorporated_SCM.Services;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using II_VI_Incorporated_SCM.Models.NCR;
using System;
using System.Web;
using System.IO;
using System.Configuration;
using System.Diagnostics.Eventing.Reader;
using System.Linq;
using Microsoft.AspNet.Identity;
using II_VI_Incorporated_SCM.Models.TaskManagement;
using System.Data.Entity.Validation;
using System.Web.Script.Serialization;
using Newtonsoft.Json;

namespace II_VI_Incorporated_SCM.Controllers.NCR
{
    [Authorize]
    public class WriteNCRForIQCController : Controller
    {
        private readonly IReciverService _IReciverService;
        private readonly ICCNService _iCCNService;
        private readonly IUserService _IUserService;
        private readonly INCRManagementService _INCRManagementService;
        private readonly IEmailService _emailService;

        public WriteNCRForIQCController(IReciverService IReciverService, ICCNService iCCNService, IUserService IUserService, INCRManagementService INCRManagementService, IEmailService emailService)
        {
            _IReciverService = IReciverService;
            _iCCNService = iCCNService;
            _IUserService = IUserService;
            _INCRManagementService = INCRManagementService;
            _emailService = emailService;
        }

        // GET: WriteNCRForIQC0


        public JsonResult GetdropdownDecriptT()
        {
            var list = _IReciverService.GetDropdowndecript();
            return Json(list);
        }

        public JsonResult GetdropdownDeCript(List<string> id,string ccn)
        {
            var listnc = _IReciverService.GetDropdownlistDecript1(id,ccn);
            return Json(listnc);
        }

        public JsonResult GetDropdownlistIQC(List<string> id)
        {
            var listnc = _IReciverService.GetDropdownlistIQC(id);
            return Json(listnc);
        }

        [Authorize(Roles = "CreateNCR")]
        public ActionResult CreateNCR(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                ViewBag.ID_CCN = id;
                ViewBag.IsOPE = _IUserService.CheckGroupRoleForUser(User.Identity.GetUserId(), UserGroup.OPE);
                List<SelectList> List = new List<SelectList>();
                SelectList ListQTYASS = new SelectList(_IUserService.GetListUserQTYASS("QUALITY ASSURANCE"), "Id", "FullName");
                SelectList ListENGINEERING = new SelectList(_IUserService.GetListUserQTYASS("ENGINEERING"), "Id", "FullName");
                SelectList ListAFGASSYE = new SelectList(_IUserService.GetListUserQTYASS("AFG/ASSYE"), "Id", "FullName");
                SelectList ListPURCHASING = new SelectList(_IUserService.GetListUserQTYASS("PURCHASING"), "Id", "FullName");
                List.Add(ListQTYASS);
                List.Add(ListENGINEERING);
                List.Add(ListAFGASSYE);
                List.Add(ListPURCHASING);
                ViewBag.List = List;
                ViewBag.ListRole = new SelectList(_IUserService.GetSelectListAllRole(), "Id", "Name");
                ViewBag.ENGINEERINGRoleId = _IUserService.GetENGINEERINGRoleId();
                ViewBag.VNMaterialTraceabilityLink = ConfigurationManager.AppSettings["VNMaterialTraceabilityLink"];
                ViewBag.CHAIRMANRoleId = _IUserService.GetCHAIRMANRoleId();
                // ViewBag.Listdefect = _INCRManagementService.GetListInresultIqc(receiver);
                return View();
            }
            return RedirectToAction("index", "NCR");

        }

        [HttpPost]
        public JsonResult SaveNCRForIQC(NCRInIQCViewModel model)
        {
            var log = new LogWriter("WriteNCRForIQCController - SaveNCRForIQC : 85");
            //log.LogWrite(JsonConvert.SerializeObject(model));
            Random rnd = new Random();
            DateTime? dateSample;
            dateSample = null;
            double sumllns = 0;
            log.LogWrite("WriteNCRForIQCController - :90 - begin CheckDubplicateNCRCreate");
            var ncrcheck = _INCRManagementService.CheckDubplicateNCRCreate(model.RECEIVER1);
            log.LogWrite("WriteNCRForIQCController - :92 - end CheckDubplicateNCRCreate : " + ncrcheck);
            if (ncrcheck)
            {
                return Json(new { success = false, message = "NCR have existed into this receiver: " + model.RECEIVER1 });
            }
            else
            {
                var logelse = new LogWriter("WriteNCRForIQCController - :101 ---------------Log Else------------------");
                var iduser = User.Identity.GetUserId();
                string ncrnumauto = _INCRManagementService.GetAutoNCRNUM("I");
                logelse.LogWrite("WriteNCRForIQCController - :90 - end CheckDubplicateNCRCreate" + ncrnumauto);

                var ReceicerResult = _IReciverService.GetListReciver(model.RECEIVER1, model.MI_PART_NO1,model.CCN1);
                logelse.LogWrite("WriteNCRForIQCController - :106 - end GetListReciver");
                //logelse.LogWrite(JsonConvert.SerializeObject(ReceicerResult));

                var listpartial = _IReciverService.GetListPartial(model.RECEIVER1);
                logelse.LogWrite("WriteNCRForIQCController - :109 - end GetListPartial");
                //logelse.LogWrite(JsonConvert.SerializeObject(listpartial));

                foreach (var item in listpartial)
                {
                    sumllns = Convert.ToDouble(item.PartialIns + sumllns);
                }
                var isSubmitted = _IUserService.CheckGroupRoleForUser(User.Identity.GetUserId(), UserGroup.OPE)
                                  & _IUserService.ISENGINEERING(model.UserApprove);
                logelse.LogWrite("WriteNCRForIQCController - :120 - isSubmitted: " + isSubmitted);

                try
                {
                    logelse.LogWrite("WriteNCRForIQCController - :125 - Begin : ");
                    List<NCR_EVI> nCR_EVIs = new List<NCR_EVI>();
                    List<NCR_DET> nCR_DETs = new List<NCR_DET>();
                    List<APPROVAL> aPPROVALs = new List<APPROVAL>();
                    List<TaskManagementCreateModel> taskManagementCreateModels = new List<TaskManagementCreateModel>();
                    VNMaterialTraceability vNMaterialTraceability = new VNMaterialTraceability();
                    NCR_HDR ncr_hdr = new NCR_HDR
                    {
                        AQL = model.AQL_VISUAL1.Trim(),
                        SAMPLE_INSP = model.AQL_VISUAL1 == AQLText.AQLinDB ? true : false,
                        PERCENT_INSP = model.AQL_VISUAL1 == AQLText.AQL100 ? true : false,
                        LEVEL = ReceicerResult.SKIP_LEVEL,
                        LOT = model.LOT1.Trim(),
                        MI_PART_NO = model.MI_PART_NO1.Trim(),
                        CCN = model.CCN1.Trim(),
                        PO_NUM = model.PO_NUM1.Trim(),
                        RECEIVER = model.RECEIVER1.Trim(),
                        REC_QTY = model.REC_QTY1,
                        REJ_QTY = model.REJ_QTY1,
                        INS_QTY = sumllns,
                        SEC = NCRType.IQC,
                        STATUS = isSubmitted ? StatusInDB.Submitted : StatusInDB.Created,
                        DATESUBMIT = isSubmitted ? DateTime.Now : dateSample,
                        USERSUBMIT = isSubmitted ? iduser : null,
                        TYPE_NCR = NCRType.IQC,
                        NCR_NUM = ncrnumauto.Trim(),
                        INS_DATE = DateTime.Now,
                        INSPECTOR = User.Identity.GetUserId(),
                        MODEL_NO = ReceicerResult.MODEL_NO,
                        VENDOR = ReceicerResult.VENDOR,
                        VEN_NAME = ReceicerResult.VEN_NAME,
                        ITEM_DESC = ReceicerResult.ITEM_DESC,
                        VEN_ADD = ReceicerResult.VEN_ADD,
                        DRAW_REV = ReceicerResult.DRAW_REV,
                        ZIP_CODE = ReceicerResult.ZIP,
                        FIRST_ARTICLE = model.FIRST_ARTICLE1,
                        CITY = ReceicerResult.CTRY,
                        STATE = ReceicerResult.STATE,
                        DEFECTIVE = model.defective,
                        Comment = model.Comment
                    };
                    //logelse.LogWrite("WriteNCRForIQCController - :160 : " + Environment.NewLine + JsonConvert.SerializeObject(ncr_hdr));
                    if (model.VNMaterialTraceability != null)
                    {
                        logelse.LogWrite("WriteNCRForIQCController - :163 : SaveFile VNMaterialTraceability");
                        string File_Upload_Url = SaveFile(model.VNMaterialTraceability);
                        vNMaterialTraceability.Id = Guid.NewGuid().ToString();
                        vNMaterialTraceability.IsPrint = true;
                        vNMaterialTraceability.NCRNUM = ncrnumauto.Trim();
                        vNMaterialTraceability.VNMaterialTraceability1 = File_Upload_Url;
                       // SizeOfFile += model.VNMaterialTraceability.ContentLength;
                        //logelse.LogWrite("WriteNCRForIQCController - :171 - VNMaterialTraceability: " + Environment.NewLine + JsonConvert.SerializeObject(VNMaterialTraceability));
                    }

                    if (model.ModelEvidence != null || model.ModelEvidence.Count > 0)
                    {
                        logelse.LogWrite("WriteNCRForIQCController - :176 : model.ModelEvidence: " + model.ModelEvidence.Count);
                        foreach (var item in model.ModelEvidence)
                        {
                            //logelse.LogWrite("WriteNCRForIQCController - :179 : SaveFile VNMaterialTraceability " + Environment.NewLine + JsonConvert.SerializeObject(item));
                            if(item != null)

DMS Web Source/II-VI Incorporated SCM/Views/WriteNCRForIQC/ListResult.cshtml
@model List<II_VI_Incorporated_SCM.Models.INS_RESULT_DEFECT>
@{
    var i = 1;
}
<table class="table table-striped table-bordered table-hover table-checkable order-column" id="tbl-res">
    <thead>
    <tr>
        <th>ITEM</th>
        <th>QTY</th>
        <th>DEFECT</th>
        <th>DECRIPTION</th>
        <th>REMARK</th>
    </tr>
    </thead>
    <tbody>
    <tr class="odd">
        @foreach (var item in Model)
        {
            i++;
            <td>@i</td>
            <td>@item.NC_Qty</td>
            <td>
                @Html.Action("GetdropdownDefect", "WriteNcrForIqc")
            </td>
            <td>
                @*@Html.Action("GetdropdownDeCript","WriteNcrForIqc")*@
            </td>
            <td><textarea type="text" name="remark"></textarea></td>
        }

    </tr>
    </tbody>
</table>

DMS Web Source/II-VI Incorporated SCM/Views/WriteNCRForIQC/_SearchForIQC.cshtml
@using (Html.BeginForm("Index", "WriteNCRForIQC", FormMethod.Post))
{
    <div class="row">
        <div class="portlet light bordered">
            <div class="portlet-title tabbable-line">
                <div class="caption">
                    <ul class="nav nav-tabs">
                        <li class="active">
                            <a href="#SearchForIQCByReceiver" data-toggle="tab" aria-expanded="true" id="iqcReceiver">Receiver</a>
                        </li>
                        <li class="">
                            <a href="#SearchForIQCByPONumber" data-toggle="tab" aria-expanded="false" id="iqcPoNumber">PO Number</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="portlet-body form">
                <div class="tab-content">
                    <div class="tab-pane active" id="SearchForIQCByReceiver">
                        @Html.Partial("~/Views/WriteNCRForIQC/_SearchForIQCByReceiver.cshtml")
                    </div>
                    <div class="tab-pane" id="SearchForIQCByPONumber">
                        @Html.Partial("~/Views/WriteNCRForIQC/_SearchForIQCByPONumBer.cshtml")
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div>
    </div>
}

DMS Web Source/II-VI Incorporated SCM/Views/WriteNCRForIQC/_SearchForIQCByPONumBer.cshtml
<div class="form-horizontal" role="form">
    <div class="form-body">
        <div class="form-group">
            <label class="col-md-4 control-label">PO</label>
            <div class="col-md-4">
                <input type="text" class="form-control ms-poser" name="RECEIVER" required="required" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-4 control-label">Part Number</label>
            <div class="col-md-4">
                <input type="text" class="form-control ms-pnser" required="required" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-4 control-label">LOT</label>
            <div class="col-md-4">
                <input type="text" class="form-control ms-lotser" required="required" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-4 col-md-4">
                <a class="btn green ms-po-number"><i class="fa fa-search"></i> Go</a>
            </div>
        </div>
    </div>
</div>
<div class="ms-updatepo-data" style="display: none">
    <div class="row top-buffer">
        <div class="col-md-4  text-center">
            <b>Receiver:</b>
        </div>
        <div class="col-md-6">
            <input class="form-control" readonly="readonly" type="text" name="RECEVER" style="text-align: center" id="RECCP" />
        </div>
    </div>
    <div class="row top-buffer">
        <div class="col-md-4  text-center">
            <b>PO Number:</b>
        </div>
        <div class="col-md-6">
            <input class="form-control" readonly="readonly" type="text" name="PO_NUM" style="text-align: center" id="POCP" />
        </div>
    </div>
    <div class="row top-buffer">
        <div class="col-md-4  text-center">
            <b>Part Number:</b>
        </div>
        <div class="col-md-6">
            <input type="text" readonly="readonly" class="form-control" name="ITEM" style="text-align: center" id="ITEMCP" />
        </div>
    </div>
    <div class="row top-buffer">
        <div class="col-md-4  text-center">
            <b>LOT Number:</b>
        </div>
        <div class="col-md-6">
            <input type="text" readonly="readonly" class="form-control" name="LOT" style="text-align: center" id="LOTCP" />
        </div>
    </div>
    <div class="row top-buffer">
            <div class="col-md-4  text-center">
            <b>REC Quantity:</b>
        </div>
        <div class="col-md-6">
            <input type="text" readonly="readonly" class="form-control" style="text-align: center" id="QTYCP" />
        </div>
    </div>
    <div class="row top-buffer">
        <div class="col-md-4 text-center">
            <b>Unit:</b>
        </div>
    </div>
    <div class="row top-buffer">
        <div class="col-md-4  text-center">
            <b>AQL Visual:</b>
        </div>
        <div class="col-md-6">
            <input type="text" readonly="readonly" class="form-control" name="AQL_VISUAL" style="text-align: center" id="AQLVCP" />
        </div>
    </div>
    <div class="row top-buffer">
        <div class="col-md-4  text-center">
            <b>SPL Visual:</b>
        </div>
        <div class="col-md-6">
            <input type="text" readonly="readonly" class="form-control" name="SAMPLING_VISUAL" style="text-align: center" id="SPLVCP" />
        </div>
    </div>
    <div class="row top-buffer">
        <div class="col-md-4  text-center">
            <b>AQL MEASURE:</b>
        </div>
        <div class="col-md-6">
            <input type="text" readonly="readonly" class="form-control" name="AQL_MEASURE" style="text-align: center" id="AQLMCP" />
        </div>
    </div>
    <div class="row top-buffer">
        <div class="col-md-4  text-center">
            <b>SPL MEASURE:</b>
        </div>
        <div class="col-md-6">
            <input type="text" readonly="readonly" class="form-control" style="text-align: center" name="SAMPLING_MEASURE" id="SPLMCP" />
        </div>
    </div>
</div>
<script>
    var urlpo = '@Url.Action("GetDetailNCRForIqcSearch", "WriteNcrForIqc")';
    $('.ms-po-number').click(function () {
        var partnum = $('.ms-pnser').val();
        var po = $('.ms-poser').val();
        var lot = $('.ms-lotser').val();
        let CCN = $('#CCN').val();
        if (isBlank(po)) {
            $('.ms-poser').addClass("input-validation-error");
            return;
        } else {
            $('.ms-poser').removeClass("input-validation-error");
        }

        if (isBlank(partnum)) {
            $('.ms-pnser').addClass("input-validation-error");
            return;
        } else {
            $('.ms-pnser').removeClass("input-validation-error");
        }
        
        if (isBlank(lot)) {
            $('.ms-lotser').addClass("input-validation-error");
            return;
        } else {
            $('.ms-lotser').removeClass("input-validation-error");
        }
        $.blockUI();
        $.post(Urliqc,
            { po: po, partnum: partnum, lot: lot,CCN:CCN },
            function (result) {
                if (result.success) {
                    $("#LOTCP").val(result.model.LOT);
                    $("#RECCP").val(result.model.RECEIVER1);
                    $("#QTYCP").val(result.model.REC_QTY);
                    $("#POCP").val(result.model.PO_NUM);
                    $("#ITEMCP").val(result.model.ITEM);
                    $("#AQLVCP").val(result.model.AQL_VISUAL);
                    $("#SPLVCP").val(result.model.SAMPLING_VISUAL);
                    $("#AQLMCP").val(result.model.AQL_MEASURE);
                    $("#SPLMCP").val(result.model.SAMPLING_MEASURE);
                    $("#INSP").val(result.model.INS_QTY);
                    $('.ms-updatepo-data').show();
                }
                else {
                    bootbox.alert(result.message);
                }
            }).fail(function () {
                bootbox.alert('Please contact to Administrator!');
            }).always(function () {
                $.unblockUI();
            });
    })
</script>

DMS Web Source/II-VI Incorporated SCM/Views/WriteNCRForIQC/_SearchForIQCByReceiver.cshtml
<div class="form-horizontal" role="form">
    <div class="form-body">
        <div class="form-group">
            <label class="col-md-4 control-label">Receiver</label>
            <div class="col-md-4">
                <input type="text" class="form-control ms-rciqcsearch" required="required" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-4 control-label">Part Number</label>
            <div class="col-md-4">
                <input type="text" class="form-control ms-pniqcsearch" required="required" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-4 col-md-4">
                <button class="btn green ms-go-reciver" type="button"><i class="fa fa-search "></i> Go</button>
            </div>
        </div>
    </div>
</div>
<div class="ms-update-data" style="display: none">
    <div class="row top-buffer">
        <div class="col-md-4 text-center">
            <b>Receiver:</b>
        </div>
        <div class="col-md-6">
            <input type="text" readonly="readonly" class="form-control" name="RECEVER" style="text-align: center" id="RECC" />
        </div>
    </div>
    <div class="row top-buffer">
        <div class="col-md-4  text-center">
            <b>PO Number:</b>
        </div>
        <div class="col-md-6">
            <input type="text" readonly="readonly" class="form-control" name="PO_NUM" style="text-align: center" id="POC" />
        </div>
    </div>
    <div class="row top-buffer">
        <div class="col-md-4  text-center">
            <b>Part Number:</b>
        </div>
        <div class="col-md-6">
            <input type="text" readonly="readonly" class="form-control" name="ITEM" style="text-align: center" id="ITEMC" />
        </div>
    </div>
    <div class="row top-buffer">
        <div class="col-md-4  text-center">
            <b>LOT Number:</b>
        </div>
        <div class="col-md-6">
            <input type="text" readonly="readonly" class="form-control" name="LOT" style="text-align: center" id="LOTC" />
        </div>
    </div>
    <div class="row top-buffer">
        <div class="col-md-4  text-center">
            <b>REC Quantity:</b>
        </div>
        <div class="col-md-6">
            <input type="text" readonly="readonly" class="form-control" name="" style="text-align: center" id="QTYC" />
        </div>
    </div>
    <div class="row top-buffer">
        <div class="col-md-4 text-center">
            <b>Unit:</b>
        </div>
    </div>
    <div class="row top-buffer">
        <div class="col-md-4  text-center">
            <b>AQL Visual:</b>
        </div>
        <div class="col-md-6">
            <input type="text" readonly="readonly" class="form-control" name="AQL_VISUAL" style="text-align: center" id="AQLVC" />
        </div>
    </div>
    <div class="row top-buffer">
        <div class="col-md-4  text-center">
            <b>SPL Visual:</b>
        </div>
        <div class="col-md-6">
            <input type="text" readonly="readonly" class="form-control" name="SAMPLING_VISUAL" style="text-align: center" id="SPLVC" />
        </div>
    </div>
    <div class="row top-buffer">
        <div class="col-md-4 text-center">
            <b>AQL MEASURE:</b>
        </div>
        <div class="col-md-6">
            <input type="text" readonly="readonly" class="form-control" name="AQL_MEASURE" style="text-align: center" id="AQLMC" />
        </div>
    </div>
    <div class="row top-buffer">
        <div class="col-md-4  text-center">
            <b>SPL MEASURE:</b>
        </div>
        <div class="col-md-6">
            <input type="text" readonly="readonly" class="form-control" style="text-align: center" name="SAMPLING_MEASURE" id="SPLMC" />
        </div>
    </div>
</div>
<script>
    function isBlank(str) {
        return (!str || /^\s*$/.test(str));
    }
    var urlpo = '@Url.Action("GetDetailNCRForIqcSearch", "WriteNcrForIqc")';
    $('.ms-go-reciver').on('click', function () {
        var reciver = $('.ms-rciqcsearch').val();
        var partnum = $('.ms-pniqcsearch').val();
        var CCN = $('#CCN').val();
        if (isBlank(reciver)) {
            $('.ms-rciqcsearch').addClass("input-validation-error");
            return;
        } else {
            $('.ms-rciqcsearch').removeClass("input-validation-error");
        }
        if (isBlank(partnum)) {
            $('.ms-pniqcsearch').addClass("input-validation-error");
            return;
        } else {
            $('.ms-pniqcsearch').removeClass("input-validation-error");
        }

        $.blockUI();
        $.post(urlpo,
            { reciver: reciver, partnum: partnum ,CCN:CCN},
            function (result) {
                if (result.success) {
                    $("#LOTC").val(result.model.LOT.trim());
                    $("#RECC").val(result.model.RECEIVER1);
                    $("#QTYC").val(result.model.REC_QTY);
                    $("#POC").val(result.model.PO_NUM);
                    $("#ITEMC").val(result.model.ITEM);
                    $("#AQLVC").val(result.model.AQL_VISUAL);
                    $("#SPLVC").val(result.model.SAMPLING_VISUAL);
                    $("#AQLMC").val(result.model.AQL_MEASURE);
                    $("#SPLMC").val(result.model.SAMPLING_MEASURE);
                    $('.ms-update-data').show();
                }
                else {
                    bootbox.alert(result.message);
                }
            }).fail(function () {
                bootbox.alert('Please contact to Administrator!');
            }).always(function () {
                $.unblockUI();
            });
    })
</script>

DMS Web Source/II-VI Incorporated SCM/Views/WriteNCRForIQC/_SelectUserApprPartial.cshtml
@model List<SelectList>

<div class="portlet grey bordered">
    <div class="row">
        <div class="col-md-12 form-horizontal">
            <div class="col-md-6 form-group">
                <div class="col-md-12">
                    <h3 style="font-weight: bold">MARLOW MRB AUTHORIZATION 1</h3>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="col-md-6 form-group">
                <div class="col-md-6">
                    <label class="control-label" style="font-weight: bold">QUALITY ASSURANCE</label>
                </div>
                <div class="col-md-6">
                    @Html.DropDownList("qualityAss", Model[0], new { @class = "form-control" })
                </div>
            </div>
            <div class="col-md-6 form-group">
                <div class="col-md-6">
                    <label class="control-label" style="font-weight: bold">ENGINEERING</label>
                </div>
                <div class="col-md-6">
                    @Html.DropDownList("engineer", Model[1], new { @class = "form-control" })
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="col-md-6 form-group">
                <div class="col-md-6">
                    <label class="control-label" style="font-weight: bold">AFG/ASSYE</label>
                </div>
                <div class="col-md-6">
                    @Html.DropDownList("afgassy", Model[2], new { @class = "form-control" })
                </div>
            </div>
            <div class="col-md-6 form-group">
                <div class="col-md-6">
                    <label class="control-label" style="font-weight: bold">PURCHASING</label>
                </div>
                <div class="col-md-6">
                    @Html.DropDownList("purchasing", Model[3], new { @class = "form-control" })
                </div>
            </div>
        </div>
    </div>
</div>